//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERHMS.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERHMS.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager.
        /// </summary>
        internal static string AppBareTitle {
            get {
                return ResourceManager.GetString("AppBareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit ERHMS Info Manager™?.
        /// </summary>
        internal static string AppConfirmExit {
            get {
                return ResourceManager.GetString("AppConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings for ERHMS Info Manager™?.
        /// </summary>
        internal static string AppConfirmReset {
            get {
                return ResourceManager.GetString("AppConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager™ encountered an error and must shut down..
        /// </summary>
        internal static string AppError {
            get {
                return ResourceManager.GetString("AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager™ is installed in the following directory:
        ///
        ///{0}
        ///.
        /// </summary>
        internal static string AppInstallDirectory {
            get {
                return ResourceManager.GetString("AppInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager™.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected assignments?.
        /// </summary>
        internal static string AssignmentConfirmRemove {
            get {
                return ResourceManager.GetString("AssignmentConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected dashboard?.
        /// </summary>
        internal static string CanvasConfirmDelete {
            get {
                return ResourceManager.GetString("CanvasConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2018 National Institute for Occupational Safety and Health (NIOSH)
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///    http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source already exists. Add it to the list of data sources?.
        /// </summary>
        internal static string DataSourceConfirmAddExisting {
            get {
                return ResourceManager.GetString("DataSourceConfirmAddExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists. Add a data source using this database?.
        /// </summary>
        internal static string DataSourceConfirmAddForDatabase {
            get {
                return ResourceManager.GetString("DataSourceConfirmAddForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data source? This will close the current data source..
        /// </summary>
        internal static string DataSourceConfirmCloseAndOpen {
            get {
                return ResourceManager.GetString("DataSourceConfirmCloseAndOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected data source?.
        /// </summary>
        internal static string DataSourceConfirmRemove {
            get {
                return ResourceManager.GetString("DataSourceConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source could not be opened. Remove it from the list of data sources?.
        /// </summary>
        internal static string DataSourceConfirmRemoveUnopenable {
            get {
                return ResourceManager.GetString("DataSourceConfirmRemoveUnopenable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen the previously used data source {0}?.
        /// </summary>
        internal static string DataSourceConfirmReopen {
            get {
                return ResourceManager.GetString("DataSourceConfirmReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected data source was created in an older version of ERHMS Info Manager™. Upgrade this data source? This may make the data source inaccessible to other users with older versions of ERHMS Info Manager™..
        /// </summary>
        internal static string DataSourceConfirmUpgrade {
            get {
                return ResourceManager.GetString("DataSourceConfirmUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source has been created..
        /// </summary>
        internal static string DataSourceCreated {
            get {
                return ResourceManager.GetString("DataSourceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create data source..
        /// </summary>
        internal static string DataSourceCreateFailed {
            get {
                return ResourceManager.GetString("DataSourceCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating data source ….
        /// </summary>
        internal static string DataSourceCreating {
            get {
                return ResourceManager.GetString("DataSourceCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected data source was created in a newer version of ERHMS Info Manager™. Please upgrade to the latest version of ERHMS Info Manager™ to open this data source..
        /// </summary>
        internal static string DataSourceNewerVersion {
            get {
                return ResourceManager.GetString("DataSourceNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source has been opened..
        /// </summary>
        internal static string DataSourceOpened {
            get {
                return ResourceManager.GetString("DataSourceOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open data source..
        /// </summary>
        internal static string DataSourceOpenFailed {
            get {
                return ResourceManager.GetString("DataSourceOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source has been upgraded..
        /// </summary>
        internal static string DataSourceUpgraded {
            get {
                return ResourceManager.GetString("DataSourceUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading data source ….
        /// </summary>
        internal static string DataSourceUpgrading {
            get {
                return ResourceManager.GetString("DataSourceUpgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may be unsaved changes. Are you sure you want to close {0}?.
        /// </summary>
        internal static string DocumentConfirmCloseDirty {
            get {
                return ResourceManager.GetString("DocumentConfirmCloseDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure email settings..
        /// </summary>
        internal static string EmailConfigure {
            get {
                return ResourceManager.GetString("EmailConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string EmailRecipientAddressInvalid {
            get {
                return ResourceManager.GetString("EmailRecipientAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a responder or enter an email address..
        /// </summary>
        internal static string EmailRecipientNotSpecified {
            get {
                return ResourceManager.GetString("EmailRecipientNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email. Please verify email settings..
        /// </summary>
        internal static string EmailSendFailed {
            get {
                return ResourceManager.GetString("EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery to the following recipients failed:
        ///
        ///{0}.
        /// </summary>
        internal static string EmailSendFailedForRecipients {
            get {
                return ResourceManager.GetString("EmailSendFailedForRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email ….
        /// </summary>
        internal static string EmailSending {
            get {
                return ResourceManager.GetString("EmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of web survey link to append (multiple-use or single-use)..
        /// </summary>
        internal static string EmailUrlTypeNotSelected {
            get {
                return ResourceManager.GetString("EmailUrlTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a form to append a web survey link..
        /// </summary>
        internal static string EmailViewNotSelected {
            get {
                return ResourceManager.GetString("EmailViewNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, you must open or create a data source. Click Open or Add &gt; New on the Data Sources screen..
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected incident?.
        /// </summary>
        internal static string IncidentConfirmDelete {
            get {
                return ResourceManager.GetString("IncidentConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual end date must be later than start date..
        /// </summary>
        internal static string IncidentEndDateActualInvalid {
            get {
                return ResourceManager.GetString("IncidentEndDateActualInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated end date must be later than start date..
        /// </summary>
        internal static string IncidentEndDateEstimateInvalid {
            get {
                return ResourceManager.GetString("IncidentEndDateEstimateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected role?.
        /// </summary>
        internal static string IncidentRoleConfirmDelete {
            get {
                return ResourceManager.GetString("IncidentRoleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected role is in use and may not be deleted..
        /// </summary>
        internal static string IncidentRoleDeleteProhibited {
            get {
                return ResourceManager.GetString("IncidentRoleDeleteProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident has been saved..
        /// </summary>
        internal static string IncidentSaved {
            get {
                return ResourceManager.GetString("IncidentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected job?.
        /// </summary>
        internal static string JobConfirmDelete {
            get {
                return ResourceManager.GetString("JobConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be later than start date..
        /// </summary>
        internal static string JobEndDateInvalid {
            get {
                return ResourceManager.GetString("JobEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected locations?.
        /// </summary>
        internal static string JobLocationConfirmRemove {
            get {
                return ResourceManager.GetString("JobLocationConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected responders?.
        /// </summary>
        internal static string JobResponderConfirmRemove {
            get {
                return ResourceManager.GetString("JobResponderConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has been saved..
        /// </summary>
        internal static string JobSaved {
            get {
                return ResourceManager.GetString("JobSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected teams?.
        /// </summary>
        internal static string JobTeamConfirmRemove {
            get {
                return ResourceManager.GetString("JobTeamConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MATERIAL EMBODIED IN THIS SOFTWARE IS PROVIDED TO YOU &quot;AS-IS&quot; AND WITHOUT
        ///WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT
        ///LIMITATION, ANY WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT
        ///SHALL THE CENTERS FOR DISEASE CONTROL AND PREVENTION (CDC) OR THE UNITED
        ///STATES (U.S.) GOVERNMENT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT,
        ///SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY
        ///DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION, LOSS OF PROF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager™ License.
        /// </summary>
        internal static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected location?.
        /// </summary>
        internal static string LocationConfirmDelete {
            get {
                return ResourceManager.GetString("LocationConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address could not be located..
        /// </summary>
        internal static string LocationGeolocateEmpty {
            get {
                return ResourceManager.GetString("LocationGeolocateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate address. Please verify mapping settings..
        /// </summary>
        internal static string LocationGeolocateFailed {
            get {
                return ResourceManager.GetString("LocationGeolocateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has been saved..
        /// </summary>
        internal static string LocationSaved {
            get {
                return ResourceManager.GetString("LocationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected logs?.
        /// </summary>
        internal static string LogConfirmDelete {
            get {
                return ResourceManager.GetString("LogConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs have been packaged..
        /// </summary>
        internal static string LogPackaged {
            get {
                return ResourceManager.GetString("LogPackaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging logs ….
        /// </summary>
        internal static string LogPackaging {
            get {
                return ResourceManager.GetString("LogPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                      NOTICE
        ///
        ///The end-user documentation included with the redistribution, if any, must
        ///include the following acknowledgment: &quot;This derivative product includes ERHMS
        ///Info Manager™ and Epi Info™ software developed by NIOSH and CDC, which can be
        ///found at http://www.cdc.gov/niosh/topics/erhms/ and
        ///http://www.cdc.gov/epiinfo/index.html.&quot;
        ///.
        /// </summary>
        internal static string NOTICE {
            get {
                return ResourceManager.GetString("NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected analysis?.
        /// </summary>
        internal static string PgmConfirmDelete {
            get {
                return ResourceManager.GetString("PgmConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected responder?.
        /// </summary>
        internal static string ResponderConfirmDelete {
            get {
                return ResourceManager.GetString("ResponderConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the selected potentially duplicate responders?.
        /// </summary>
        internal static string ResponderPairConfirmIgnore {
            get {
                return ResourceManager.GetString("ResponderPairConfirmIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responders have been merged..
        /// </summary>
        internal static string ResponderPairMerged {
            get {
                return ResourceManager.GetString("ResponderPairMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select two responders to merge..
        /// </summary>
        internal static string ResponderPairNotSelected {
            get {
                return ResourceManager.GetString("ResponderPairNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No potentially duplicate responders found. You may still perform a merge by selecting two responders from the list and clicking Merge &gt; Selected..
        /// </summary>
        internal static string ResponderPairSearchEmpty {
            get {
                return ResourceManager.GetString("ResponderPairSearchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for potentially duplicate responders ….
        /// </summary>
        internal static string ResponderPairSearching {
            get {
                return ResourceManager.GetString("ResponderPairSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder has been saved..
        /// </summary>
        internal static string ResponderSaved {
            get {
                return ResourceManager.GetString("ResponderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following directory already exists:
        ///
        ///{0}
        ///
        ///Are you sure you want to use this location?.
        /// </summary>
        internal static string RootPathDirectoryExists {
            get {
                return ResourceManager.GetString("RootPathDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager™ failed to initialize the following directory:
        ///
        ///{0}
        ///
        ///Please choose another location..
        /// </summary>
        internal static string RootPathInitializeFailed {
            get {
                return ResourceManager.GetString("RootPathInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a location for your application files. We&apos;ll create a directory named ERHMS Info Manager in that location..
        /// </summary>
        internal static string RootPathInstructions {
            get {
                return ResourceManager.GetString("RootPathInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected responders?.
        /// </summary>
        internal static string RosterConfirmRemove {
            get {
                return ResourceManager.GetString("RosterConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the root directory? This may cause existing data sources to stop working properly. ERHMS Info Manager™ will attempt to copy your application files and restart when settings are saved..
        /// </summary>
        internal static string SettingsConfirmChangeRootDirectory {
            get {
                return ResourceManager.GetString("SettingsConfirmChangeRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERHMS Info Manager™ failed to initialize the following directory:
        ///
        ///{0}
        ///
        ///Settings have not been saved..
        /// </summary>
        internal static string SettingsInitializeFailed {
            get {
                return ResourceManager.GetString("SettingsInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been saved..
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected team?.
        /// </summary>
        internal static string TeamConfirmDelete {
            get {
                return ResourceManager.GetString("TeamConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected responders?.
        /// </summary>
        internal static string TeamResponderConfirmRemove {
            get {
                return ResourceManager.GetString("TeamResponderConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team has been saved..
        /// </summary>
        internal static string TeamSaved {
            get {
                return ResourceManager.GetString("TeamSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected template?.
        /// </summary>
        internal static string TemplateConfirmDelete {
            get {
                return ResourceManager.GetString("TemplateConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following fields are {0}:
        ///
        ///{1}.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected form?.
        /// </summary>
        internal static string ViewConfirmDelete {
            get {
                return ResourceManager.GetString("ViewConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following fields are unsupported for publication to {0}:
        ///
        ///{1}.
        /// </summary>
        internal static string ViewFieldUnsupported {
            get {
                return ResourceManager.GetString("ViewFieldUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Please verify web survey settings..
        /// </summary>
        internal static string WebConfigure {
            get {
                return ResourceManager.GetString("WebConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more records could not be linked to a responder. Review these records?.
        /// </summary>
        internal static string WebConfirmReviewUnlinkable {
            get {
                return ResourceManager.GetString("WebConfirmReviewUnlinkable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve web survey details. Please verify web survey settings..
        /// </summary>
        internal static string WebGetSurveyFailed {
            get {
                return ResourceManager.GetString("WebGetSurveyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving web survey details ….
        /// </summary>
        internal static string WebGettingSurvey {
            get {
                return ResourceManager.GetString("WebGettingSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been imported from web..
        /// </summary>
        internal static string WebImported {
            get {
                return ResourceManager.GetString("WebImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import data from web. Please verify web survey settings..
        /// </summary>
        internal static string WebImportFailed {
            get {
                return ResourceManager.GetString("WebImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing data from web ….
        /// </summary>
        internal static string WebImporting {
            get {
                return ResourceManager.GetString("WebImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form has been published to web..
        /// </summary>
        internal static string WebPublished {
            get {
                return ResourceManager.GetString("WebPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to publish form to web. Please verify web survey settings..
        /// </summary>
        internal static string WebPublishFailed {
            get {
                return ResourceManager.GetString("WebPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing form to web ….
        /// </summary>
        internal static string WebPublishing {
            get {
                return ResourceManager.GetString("WebPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be later than start date..
        /// </summary>
        internal static string WebSurveyEndDateInvalid {
            get {
                return ResourceManager.GetString("WebSurveyEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected form has not yet been published to web..
        /// </summary>
        internal static string WebViewNotPublished {
            get {
                return ResourceManager.GetString("WebViewNotPublished", resourceCulture);
            }
        }
    }
}
