CREATE TABLE ERHMS_Roles (
	RoleId NVARCHAR(255) NOT NULL PRIMARY KEY,
	Name TEXT NOT NULL
);

INSERT INTO ERHMS_Roles (RoleId, Name) VALUES ('bab4d58b-9758-403c-8c5f-ad56f7093a1f', 'Command');
INSERT INTO ERHMS_Roles (RoleId, Name) VALUES ('305b15dc-87ee-430c-9871-291e6e0da2ee', 'Operations');
INSERT INTO ERHMS_Roles (RoleId, Name) VALUES ('2746793a-6c6f-48f1-9edb-93fc3c1ac6fb', 'Planning');
INSERT INTO ERHMS_Roles (RoleId, Name) VALUES ('a5ed1015-929f-41d3-9263-07c3e1d8b133', 'Logistics');
INSERT INTO ERHMS_Roles (RoleId, Name) VALUES ('4a23bc15-b9db-49e4-b984-9ddd1fb87191', 'Administration');

CREATE TABLE ERHMS_IncidentRoles (
	IncidentRoleId NVARCHAR(255) NOT NULL PRIMARY KEY,
	IncidentId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Incidents (IncidentId),
	Name TEXT NOT NULL
);

CREATE TABLE ERHMS_Teams (
	TeamId NVARCHAR(255) NOT NULL PRIMARY KEY,
	IncidentId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Incidents (IncidentId),
	Name TEXT NOT NULL,
	Description TEXT
);

CREATE TABLE ERHMS_TeamResponders (
	TeamResponderId NVARCHAR(255) NOT NULL PRIMARY KEY,
	TeamId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Teams (TeamId),
	ResponderId NVARCHAR(255) NOT NULL REFERENCES Responders (GlobalRecordId),
	IncidentRoleId NVARCHAR(255) REFERENCES ERHMS_IncidentRoles (IncidentRoleId)
);

CREATE TABLE ERHMS_Jobs (
	JobId NVARCHAR(255) NOT NULL PRIMARY KEY,
	IncidentId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Incidents (IncidentId),
	Name TEXT NOT NULL,
	Description TEXT,
	StartDate DATETIME,
	EndDate DATETIME
);

CREATE TABLE ERHMS_JobLocations (
	JobLocationId NVARCHAR(255) NOT NULL PRIMARY KEY,
	JobId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Jobs (JobId),
	LocationId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Locations (LocationId)
);

CREATE TABLE ERHMS_JobTeams (
	JobTeamId NVARCHAR(255) NOT NULL PRIMARY KEY,
	JobId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Jobs (JobId),
	TeamId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Teams (TeamId)
);

CREATE TABLE ERHMS_JobResponders (
	JobResponderId NVARCHAR(255) NOT NULL PRIMARY KEY,
	JobId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Jobs (JobId),
	ResponderId NVARCHAR(255) NOT NULL REFERENCES Responders (GlobalRecordId),
	IncidentRoleId NVARCHAR(255) REFERENCES ERHMS_IncidentRoles (IncidentRoleId)
);

CREATE TABLE ERHMS_JobNotes (
	JobNoteId NVARCHAR(255) NOT NULL PRIMARY KEY,
	JobId NVARCHAR(255) NOT NULL REFERENCES ERHMS_Jobs (JobId),
	Content TEXT NOT NULL,
	[Date] DATETIME NOT NULL
);
