CREATE TABLE ERHMS_WebLinks (
	WebLinkId NVARCHAR(255) NOT NULL PRIMARY KEY,
	ResponderId NVARCHAR(255) NOT NULL REFERENCES Responders (GlobalRecordId),
	SurveyId NVARCHAR(255) NOT NULL,
	GlobalRecordId NVARCHAR(255) NOT NULL
);
